-- Extracted from CECMS_Schema.pdf

CREATE TABLE STUDENT (
  STUDENT_ID INT PRIMARY KEY,
  ROLL_NO VARCHAR(20) UNIQUE,
  FULL_NAME VARCHAR(150),
  EMAIL VARCHAR(150) UNIQUE,
  DEPARTMENT VARCHAR(100),
  ACADEMIC_YEAR INT,
  PHONE VARCHAR(20)
);

CREATE TABLE CLUB (
  CLUB_ID INT PRIMARY KEY,
  CLUB_NAME VARCHAR(150),
  CLUB_TYPE VARCHAR(50),
  DESCRIPTION VARCHAR(1000),
  FACULTY_ADVISOR VARCHAR(150),
  CREATED_DATE DATE
);

CREATE TABLE VENUE (
  VENUE_ID INT PRIMARY KEY,
  VENUE_NAME VARCHAR(200),
  LOCATION VARCHAR(250),
  CAPACITY INT,
  VENUE_TYPE VARCHAR(50)
);

CREATE TABLE EVENT (
  EVENT_ID INT PRIMARY KEY,
  EVENT_TITLE VARCHAR(200),
  EVENT_TYPE VARCHAR(50),
  DESCRIPTION VARCHAR(1000),
  START_DATETIME DATETIME,
  END_DATETIME DATETIME,
  REGISTRATION_TYPE VARCHAR(20),
  MAX_CAPACITY INT,
  FEE DECIMAL(10,2),
  CLUB_ID INT,
  VENUE_ID INT,
  FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
  FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID)
);

CREATE TABLE CLUB_MEMBERSHIP (
  MEMBERSHIP_ID INT PRIMARY KEY,
  STUDENT_ID INT,
  CLUB_ID INT,
  ROLE VARCHAR(50),
  JOIN_DATE DATE,
  STATUS VARCHAR(20),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
  UNIQUE (STUDENT_ID, CLUB_ID)
);

CREATE TABLE ORGANIZER_ROLE (
  ORGANIZER_ROLE_ID INT PRIMARY KEY,
  STUDENT_ID INT,
  EVENT_ID INT,
  ROLE_TYPE VARCHAR(50),
  ASSIGNED_DATE DATE,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
  UNIQUE (STUDENT_ID, EVENT_ID, ROLE_TYPE)
);

CREATE TABLE TEAM (
  TEAM_ID INT PRIMARY KEY,
  TEAM_NAME VARCHAR(150),
  EVENT_ID INT,
  LEADER_STUDENT_ID INT,
  CREATED_DATE DATE,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
  FOREIGN KEY (LEADER_STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE REGISTRATION (
  REGISTRATION_ID INT PRIMARY KEY,
  STUDENT_ID INT,
  TEAM_ID INT,
  EVENT_ID INT,
  REGISTRATION_DATE DATE,
  STATUS VARCHAR(20),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
  UNIQUE (STUDENT_ID, EVENT_ID)
);

CREATE TABLE PAYMENT (
  PAYMENT_ID INT PRIMARY KEY,
  REGISTRATION_ID INT,
  AMOUNT DECIMAL(10,2),
  PAYMENT_MODE VARCHAR(30),
  PAYMENT_STATUS VARCHAR(20),
  PAYMENT_DATE DATE,
  FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION(REGISTRATION_ID)
);

CREATE TABLE FEEDBACK (
  FEEDBACK_ID INT PRIMARY KEY,
  REGISTRATION_ID INT,
  STUDENT_ID INT,
  EVENT_ID INT,
  RATING INT,
  COMMENTS VARCHAR(2000),
  SUBMITTED_DATE DATE,
  FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION(REGISTRATION_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE SPONSOR (
  SPONSOR_ID INT PRIMARY KEY,
  SPONSOR_NAME VARCHAR(200),
  CONTACT_PERSON VARCHAR(150),
  CONTACT_EMAIL VARCHAR(150),
  CONTACT_PHONE VARCHAR(30),
  SPONSOR_TYPE VARCHAR(50)
);

CREATE TABLE SPONSORSHIP (
  SPONSORSHIP_ID INT PRIMARY KEY,
  SPONSOR_ID INT,
  CLUB_ID INT,
  EVENT_ID INT,
  AMOUNT DECIMAL(12,2),
  BENEFITS VARCHAR(1000),
  FOREIGN KEY (SPONSOR_ID) REFERENCES SPONSOR(SPONSOR_ID),
  FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE TEAM_MEMBER (
  TEAM_MEMBER_ID INT PRIMARY KEY,
  TEAM_ID INT,
  STUDENT_ID INT,
  ROLE_IN_TEAM VARCHAR(50),
  JOINED_DATE DATE,
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  UNIQUE (TEAM_ID, STUDENT_ID)
);
